# Form implementation generated from reading ui file 'FITSMetaDB26.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 417)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Description = QtWidgets.QLabel(parent=self.centralwidget)
        self.Description.setGeometry(QtCore.QRect(80, 0, 386, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Description.setFont(font)
        self.Description.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.Description.setObjectName("Description")
        self.pushButton_Folder_db = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Folder_db.setGeometry(QtCore.QRect(0, 40, 201, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Folder_db.setFont(font)
        self.pushButton_Folder_db.setObjectName("pushButton_Folder_db")
        self.label_folder_db = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_folder_db.setGeometry(QtCore.QRect(130, 70, 391, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_folder_db.setFont(font)
        self.label_folder_db.setObjectName("label_folder_db")
        self.pushButton_root_folder = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_root_folder.setGeometry(QtCore.QRect(0, 100, 291, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_root_folder.setFont(font)
        self.pushButton_root_folder.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.pushButton_root_folder.setObjectName("pushButton_root_folder")
        self.label_root_folder = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_root_folder.setGeometry(QtCore.QRect(130, 130, 381, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_root_folder.setFont(font)
        self.label_root_folder.setObjectName("label_root_folder")
        self.pushButton_create_db = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_create_db.setGeometry(QtCore.QRect(0, 170, 81, 24))
        self.pushButton_create_db.setObjectName("pushButton_create_db")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(180, 170, 221, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_view_DB = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_view_DB.setGeometry(QtCore.QRect(0, 230, 111, 24))
        self.pushButton_view_DB.setObjectName("pushButton_view_DB")
        self.pushButton_help = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(0, 270, 81, 24))
        self.pushButton_help.setObjectName("pushButton_help")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Description.setText(_translate("MainWindow", "Database for *.FITS metada and the filenames "))
        self.pushButton_Folder_db.setToolTip(_translate("MainWindow", "Folder for the SQLite DB. DB will have all the relevant filenames as well as the metadata for each image"))
        self.pushButton_Folder_db.setText(_translate("MainWindow", "1. Select folder for database file"))
        self.label_folder_db.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_root_folder.setToolTip(_translate("MainWindow", "Select folder for the images to be scanned. Sub-folders will also be scanned"))
        self.pushButton_root_folder.setText(_translate("MainWindow", "2. Select root folder for scanning of *.FITS files"))
        self.label_root_folder.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_create_db.setToolTip(_translate("MainWindow", "Scan folders as spesified abd create database"))
        self.pushButton_create_db.setText(_translate("MainWindow", "3. Create DB"))
        self.pushButton_view_DB.setToolTip(_translate("MainWindow", "Press to view database. Fields can be filtered"))
        self.pushButton_view_DB.setText(_translate("MainWindow", "4. View database"))
        self.pushButton_help.setText(_translate("MainWindow", "Help"))
